CREATE SEQUENCE SEQ_MATERIAL
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_MATERIAL (
    MATERIAL_ID INTEGER DEFAULT SEQ_ALIMENTOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO TEXT,
    TIPO VARCHAR2(150) NOT NULL,
    PESO DECIMAL(10, 2),
    VOLUME DECIMAL(10, 2),
);