CREATE SEQUENCE SEQ_VEICULOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

 CREATE TABLE TBL_VEICULOS (
    ID INTEGER DEFAULT SEQ_VEICULOS.NEXTVAL NOT NULL,
    PLACA VARCHAR2(100) NOT NULL,
    CHASSI VARCHAR2(100) NOT NULL,
    QUILOMETRAGEM INTEGER(100) NOT NULL
 );